apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sAllowedRepos
metadata:
  name: only-gcr-repo-for-demo-ns
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces:
      - "demo"
  parameters:
    message: "All images must pulled from gcr.io."
    repos:
      - "nginx"
      - "gcr.io"
  enforcementAction: deny
